---
  - name: Utilities Install
    yum: pkg={{item}} state=latest update_cache=yes
    with_items:
      - wget
      - git
      - pciutils
      - bind-utils

  - name: NTP Install
    yum: pkg=ntp state=present

  - name: NTP Client Setting
    template: src=ntp.conf.j2 dest=/etc/ntp.conf backup=yes
    notify:
      - restart ntpd.service
  - name: Start NTP
    service: name=ntpd.service state=started d enabled=yes

  - name: Replace resolv.conf
    tags: resolv
    template: src=resolv.conf.j2 dest=/etc/resolv.conf backup=yes
