---
- hosts: "{{ target }}"
  vars:
    myuser: takeshi
    rstudio: rstudio-server-0.98.1103-amd64.deb
    ntp_srv_addr: 192.168.0.2

# vars_prompt:
#   myuser: "Enter username"
  user: vagrant
  sudo: yes

  tasks:
  - name: add a new user
    user: name={{myuser}} shell=/bin/bash password=$1$3FCsXQtq$EKWn6gqWXj6Gto9ogr.1s. groups=sudo append=yes
  - name: ssh pub key setting
    authorized_key: user={{myuser}} key="{{ lookup('file','/home/takeshi/Ansible/R_studio/files/secret.key.pub') }}"
  
  - name: utils install
    apt: pkg={{item}} state=latest update_cache=yes
    with_items:
      - expect
      - git
      - wget
      - dnsutils
      - bind9-host

# Set NTP Client
  - name: ntp install
    apt: pkg=ntp state=present
  - name: ntp client setting
    template: src=./files/ntp.conf.j2 dest=/etc/ntp.conf backup=yes
    notify:
      - restart ntpd
  - name: start ntp
    service: name=ntp state=started

# Install R Studio
  - name: install r-base
    apt: pkg={{item}} state=latest
    with_items:
      - r-base
      - gdebi-core
      - libapparmor1
      - libssl0.9.8
  - name: get rstudio-server
    #command: /usr/bin/wget http://download2.rstudio.org/{{rstudio}} -O /tmp/{{rstudio}} creates=/var/lib/rstudio-server/installed
    get_url: url=http://download2.rstudio.org/{{rstudio}} dest=/tmp/{{rstudio}} owner=root
  - name: install rstudio-server
    script: ./scripts/install_rstudio-server.sh /tmp/{{rstudio}} creates=/var/lib/rstudio-server/installed
  - name: start rstudio-server
    command: /usr/lib/rstudio-server/bin/rstudio-server restart

# Handlers
  
  handlers:
  - name: restart ntpd
    service: name=ntp state=restarted

