---
- hosts: all

  vars:

  user: vagrant
  sudo: yes
 
  tasks:
    - name: Install Packages
      yum: name={{item}} state=latest 
      with_items:
        - php
        - mariadb-server
        - MySQL-python


    - name: Start and Enable MariaDB
      service: name=mariadb state=started enabled=yes
    #- name: Set root account
    #  mysql_user: name=root host=localhost password=root
    #- name: Put my.cnf
    #  template: src=my.cnf.j2 dest=/etc/my.cnf
    - name: Create Database for wordpress
      mysql_db: name=wordpress state=present
    - name: Create user for wordpress
      mysql_user: name=wordpress password=password priv="wordpress.*:ALL" host=localhost state=present

    - name: Get Wordpress
      get_url: url=http://wordpress.org/latest.tar.gz dest=/tmp/latest.tar.gz owner=root
    - name: Unarchive a file
      command: tar zxf /tmp/latest.tar.gz -C /var/www/html creates=/var/www/html/wordpress

    - name: Copy VirtualBox.run
      copy: src=./wp-config.php dest=/var/www/html/wordpress mode=0666

    - name: Start and Enable httpd
      service: name=httpd state=started enabled=yes
