- name: Changing root password
  tags: pass
  user: name=root password=root update_password=on_create

- name: Postfix stop and disable
  tags: postfix
  service: name=postfix state=stopped enabled=no

- name: Release Firewall
  tags: fw
  service: name=firewalld state=stopped enabled=no

