---
- hosts: all

  vars:
    myuser: vine
    sshpass: sshpass-1.05
    vboxpkg: VirtualBox-4.3.26-98988-Linux_amd64.run
    vagrantpkg: vagrant_1.7.2_x86_64.rpm

  user: root
 
  tasks:
    - name: Update Repository
      command: apt-get update
    - name: Dist Upgrade
      command: apt-get dist-upgrade -y
    - name: Get Packages 
      command: apt-get install {{item}} -y
      with_items:
        - python-devel
        - python-pip
        - git
        - screen
        - bind-utils

    - name: Edit grub.conf
      replace: dest=/boot/grub/menu.lst regexp='quiet' replace='quiet psmouse.proto=bare' backup=yes

    - name: System Reboot
      command: shutdown -r now
    - name: Wait for the server to go down (reboot)
      local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
    - name: Wait for the server to come up
      local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30

    - name: Copy VirtualBox.run
      copy: src=./files/{{vboxpkg}} dest=/tmp/{{vboxpkg}} mode=0755
    - name: Install VirtualBox
      command: ./{{vboxpkg}} chdir=/tmp/

    - name: Copy Vagrant rpm
      copy: src=./files/{{vagrantpkg}} dest=/tmp/{{vagrantpkg}}
    - name: Install Vagrant
      command: rpm -ivh {{vagrantpkg}} chdir=/tmp/

    - name: Add a user
      user: name={{myuser}} shell=/bin/bash password=$1$3FCsXQtq$EKWn6gqWXj6Gto9ogr.1s. 
    - name: SSH Public Key Setting
      authorized_key: user={{myuser}} key="{{ lookup('file','./secret_key.pub') }}"
      
    - name: Edit sudoers
      lineinfile: "dest=/etc/sudoers line='%{{myuser}} ALL=(ALL) NOPASSWD: ALL'"

    - name: Get and Unarchive sshpass
      unarchive: src=./files/{{sshpass}}.tar.gz dest=/tmp creates=/usr/local/bin/sshpass
    - name: Configure sshpass
      command: ./configure chdir=/tmp/{{sshpass}} creates=/usr/local/bin/sshpass
    - name: Make sshpass
      command: make chdir=/tmp/{{sshpass}}  creates=/usr/local/bin/sshpass
    - name: Install sshpass
      command: make install chdir=/tmp/{{sshpass}}  creates=/usr/local/bin/sshpass

    - name: Get Ansible
      command: git clone git://github.com/ansible/ansible.git --recursive chdir=/tmp/
    - name: Set env 
      shell: source ./hacking/env-setup chdir=/tmp/ansible
    - name: Install pip packages
      command: pip-python install paramiko PyYAML Jinja2 httplib2
    - name: Rebase
      command: git pull --rebase chdir=/tmp/ansible
    - name: Update
      command: git submodule update --init --recursive chdir=/tmp/ansible
    - name: Install Ansible
      command: make install chdir=/tmp/ansible

